const ACTIONS  = {
  GET_MESSAGE_REQUEST:'GET_MESSAGE_REQUEST',
  GET_MESSAGE_SUCCESS:'GET_MESSAGE_SUCCESS',
  GET_MESSAGE_ERROR:'GET_MESSAGE_ERROR',

  CREATE_MESSAGE_REQUEST:'CREATE_MESSAGE_REQUEST',
  CREATE_MESSAGE_SUCCESS:'CREATE_MESSAGE_SUCCESS',
  CREATE_MESSAGE_ERROR:'CREATE_MESSAGE_ERROR',  
}

export default ACTIONS;